### ISSUE TITLE
Bash code block and Typo

### ISSUE THREAD

**Issue by cs-pedro-azevedo** [cs-bruno-novo/escravizando-mac-os#1]
### Bash code block

When a command is described along the text is used a syntax code block, so to keep the pattern used for: 

``` shell
source ~/.bash_profile
```

at section "Vamos ao trabalho"...
# 
### Typo

At the last paragraph, it found a typo... 

Where we read:
"Istalaremos um componente chamado Gerenciador de hardware acelerado (Intel® HAXM)..."

Should be reading:
"Instalaremos um componente chamado Gerenciador de hardware acelerado (Intel® HAXM)..." 
# 
### General explaining

Bruno, now you can open a new branch to fix the issue, approve a pull request and close this issue :wink:.
As I said before, i thought your text fabulous, so I'm here to help make it even better, if that's possible.

Best regards.

**Comment by bruno-novo-it** [comment]
Thank you a lot for the help man, the issues have been already fixed.

**Comment by bruno-novo-it** [comment]
The code has been changed by commit:

https://github.com/cs-bruno-novo/escravizando-mac-os/commit/0cbd7c78d14f8a6bf6938e5ede3ff03d961bb85e
